spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  aop:
    # 加入@EnableAspectJAutoProxy. (引入時已經預設為開啟)
    auto: true
    # 使用CGLIB來實現AOP的時候，需要配置spring.aop.proxy-target-class=true，否則預設使用的是標準Java的實現。
    proxy-target-class: true

  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      jdbc:
        time_zone: GMT+08:00
    show-sql: true
