spring:
  datasource:
    url: jdbc:h2:mem:rex-demo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  aop:
    # 加入@EnableAspectJAutoProxy. (引入時已經預設為開啟)
    auto: true
    # 使用CGLIB來實現AOP的時候，需要配置spring.aop.proxy-target-class=true，否則預設使用的是標準Java的實現。
    proxy-target-class: true

  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      jdbc:
        time_zone: GMT+08:00
    show-sql: true
  h2:
    # console: http://localhost:8080/h2-console/
    console:
      enabled: true
